const ICON_SLUGS = {
  'C#': 'dotnet',
  'C Language': 'c',
  'C++': 'cplusplus',
  '.NET': 'dotnet',
  'Android Studio': 'androidstudio',
  'App Inventor': 'android',
  'AutoCAD 2023': 'autodesk',
  'A* Pathfinding': 'unity',
  '2D Modeling': 'autodesk',
  '3D Modeling': 'autodesk',
  'Bluetooth Protocol': 'bluetooth',
  Blueprints: 'unrealengine',
  Bootstrap: 'bootstrap',
  Cinemachine: 'unity',
  'CSV Export': 'libreofficecalc',
  Docker: 'docker',
  FastAPI: 'fastapi',
  'Epic Online Services': 'epicgames',
  Firebase: 'firebase',
  FullCalendar: 'googlecalendar',
  'Game Networking': 'unrealengine',
  'GitHub Actions': 'githubactions',
  'Google Calendar API': 'googlecalendar',
  Java: 'openjdk',
  JavaScript: 'javascript',
  JSP: 'apachetomcat',
  'Jetpack Compose': 'jetpackcompose',
  Kotlin: 'kotlin',
  'Linux Kernel': 'linux',
  Maven: 'apachemaven',
  MPAndroidChart: 'android',
  MongoDB: 'mongodb',
  MySQL: 'mysql',
  'NVIDIA DLSS': 'nvidia',
  'Next.js': 'nextdotjs',
  Multiplayer: 'unrealengine',
  PlayFab: 'epicgames',
  'Process Management': 'linux',
  PostgreSQL: 'postgresql',
  'Material Design': 'materialdesignicons',
  React: 'react',
  'Responsive Design': 'css',
  'Three.js': 'threedotjs',
  'Spring Boot': 'springboot',
  'SQL Server': 'sqlite',
  SQLAlchemy: 'sqlalchemy',
  SQLite: 'sqlite',
  'Tailwind CSS': 'tailwindcss',
  TypeScript: 'typescript',
  UMG: 'unrealengine',
  'Unreal Engine': 'unrealengine',
  'Unity 2D': 'unity',
  Vite: 'vite',
  'Windows Forms': 'dotnet',
  HTML5: 'html5',
  CSS3: 'css',
  'React Native': 'react',
  'Express.js': 'express',
  'Node.js': 'nodedotjs',
};

export const getIconSlug = (techName) => {
  if (ICON_SLUGS[techName]) return ICON_SLUGS[techName];
  return techName.toLowerCase().replace(/\s+/g, '').replace(/\./g, '');
};
