const ICON_SLUGS = {
  'C#': 'csharp',
  'C Language': 'c',
  'C++': 'cplusplus',
  '.NET': 'dotnet',
  'Android Studio': 'androidstudio',
  'App Inventor': 'appinventor',
  'AutoCAD 2023': 'autodesk',
  Bootstrap: 'bootstrap',
  Docker: 'docker',
  FastAPI: 'fastapi',
  'Epic Online Services': 'epicgames',
  Firebase: 'firebase',
  'GitHub Actions': 'githubactions',
  'Google Calendar API': 'googlecalendar',
  Java: 'openjdk',
  JavaScript: 'javascript',
  'Jetpack Compose': 'jetpackcompose',
  Kotlin: 'kotlin',
  MongoDB: 'mongodb',
  MySQL: 'mysql',
  'NVIDIA DLSS': 'nvidia',
  'Next.js': 'nextdotjs',
  PostgreSQL: 'postgresql',
  'Material Design': 'materialdesignicons',
  React: 'react',
  'Three.js': 'threedotjs',
  'Spring Boot': 'springboot',
  'SQL Server': 'microsoftsqlserver',
  SQLAlchemy: 'sqlalchemy',
  SQLite: 'sqlite',
  'Tailwind CSS': 'tailwindcss',
  TypeScript: 'typescript',
  'Unreal Engine': 'unrealengine',
  'Unity 2D': 'unity',
  Vite: 'vite',
  HTML5: 'html5',
  CSS3: 'css3',
  'React Native': 'react',
  'Express.js': 'express',
  'Node.js': 'nodedotjs',
};

export const getIconSlug = (techName) => {
  if (ICON_SLUGS[techName]) return ICON_SLUGS[techName];
  return techName.toLowerCase().replace(/\s+/g, '').replace(/\./g, '');
};
